server:
  http:
    addr: 0.0.0.0:8081
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9091
    timeout: 1s
    interceptors:
      auth:
        enabled: true
        ignoreMethods:
          - GlobalService/GetVersion
          - DemoService/Token

debug: true
swagger: true

log:
  level: info
  format: console
  deployment: true

kube:
  incluster: false
  kubeconfig: /Users/wilsonwu/.kube/config
