server:
  http:
    addr: 0.0.0.0:8081
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9091
    timeout: 1s
debug: true
swagger: true

log:
  level: info
  format: console
  deployment: true

kube:
  incluster: false
  kubeconfig:
