apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: gatepoint
  name: gatepoint
  namespace: gatepoint
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gatepoint
  namespace: gatepoint
  labels:
    app: gatepoint
rules:
  # remove the test scope
  - apiGroups: [""]
    resources: ["secrets", "pods", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gatepoint
  namespace: gatepoint
  labels:
    app: gatepoint
subjects:
  - kind: ServiceAccount
    name: gatepoint
    namespace: gatepoint
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gatepoint
---
apiVersion: v1
kind: Service
metadata:
  name: gatepoint
  namespace: gatepoint
  labels:
    app: gatepoint
    service: gatepoint
spec:
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: NodePort
  selector:
    app: gatepoint
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatepoint
  namespace: gatepoint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatepoint
  template:
    metadata:
      labels:
        app: gatepoint
    spec:
      serviceAccountName: gatepoint
      containers:
        - image: release.daocloud.io/skoala/gatepoint:0.11
          imagePullPolicy: IfNotPresent
          name: gatepoint
          ports:
            - containerPort: 8081
          volumeMounts:
            - mountPath: /config/
              name: gatepoint-config
      volumes:
        - name: gatepoint-config
          configMap:
            name: gatepoint-config
            items:
              - key: config.yaml
                path: config.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gatepoint-config
  namespace: gatepoint
data:
  config.yaml: |
    server:
      http:
        addr: 0.0.0.0:8081
        timeout: 1s
      grpc:
        addr: 0.0.0.0:9091
        timeout: 1s
    
    kubernetes:
      kubeconfig: