package service

import (
	"context"
	"fmt"
	"strconv"

	projectv1 "github.com/gatepoint/gatepoint/api/gatepoint/v1"
	generalv1 "github.com/gatepoint/gatepoint/api/general/v1"
	"github.com/gatepoint/gatepoint/pkg/utils"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/emptypb"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes"
)

type DemoService struct {
	// This is generated by protoc
	projectv1.UnimplementedDemoServer
	clientset kubernetes.Clientset
}

func NewDemoService(clientset kubernetes.Clientset) *DemoService {
	return &DemoService{clientset: clientset}
}
func (s *DemoService) Demo(ctx context.Context, req *generalv1.DemoRequest) (*generalv1.DemoResponse, error) {
	_, err := utils.AuthJWT(ctx)
	if err != nil {
		return nil, status.Error(codes.Unauthenticated, err.Error())
	}

	return &generalv1.DemoResponse{
		Demo: &generalv1.Demo{
			Demo: req.Demo,
		},
	}, nil
}

func (s *DemoService) Token(ctx context.Context, req *emptypb.Empty) (*generalv1.TokenResponse, error) {
	pods, err := s.clientset.CoreV1().Pods("").List(context.TODO(), metav1.ListOptions{})
	if err != nil {
		panic(err.Error())
	}
	fmt.Printf("There are %d pods in the cluster\n", len(pods.Items))
	accessToken, _, errGenTokens := utils.GenerateTokens(strconv.Itoa(len(pods.Items)))
	if errGenTokens != nil {
		return nil, errGenTokens
	}
	return &generalv1.TokenResponse{
		Token: accessToken,
	}, nil
}
