package service

import (
	"context"

	projectv1 "github.com/gatepoint/gatepoint/api/gatepoint/v1"
	generalv1 "github.com/gatepoint/gatepoint/api/general/v1"
	"google.golang.org/protobuf/types/known/emptypb"
)

type GlobalService struct {
	// This is generated by protoc
	projectv1.UnimplementedGlobalServiceServer
}

func NewGlobalService() *GlobalService {
	return &GlobalService{}
}

func (s *GlobalService) GetVersion(ctx context.Context, req *emptypb.Empty) (*generalv1.VersionRes, error) {
	return &generalv1.VersionRes{
		Version: "v0.0.1",
	}, nil
}
